# Generated by Django 3.0.8 on 2020-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_pic',
            field=models.ImageField(default='profile_pics/test.jpg', upload_to='jobs_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_pics/test.jpg', upload_to='profile_pics'),
        ),
    ]
